/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\assets\artgallery.gltf 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Artgallery(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('./assets/artgallery.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Art" />
        <group name="cube" position={[0, 0.082, 8.805]} />
        <mesh name="Rock001" geometry={nodes.Rock001.geometry} material={materials['Material.005']} position={[-0.03, 0, -16.226]} scale={0.001} />
        <mesh name="Wall" geometry={nodes.Wall.geometry} material={materials.Cube_BAKED} />
        <mesh name="Plant004" geometry={nodes.Plant004.geometry} material={materials['Material.006']} position={[-3.905, 0.314, -8.288]} rotation={[-2.454, -1.305, -2.473]} />
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials['Material.004']} position={[0, 0, 16.237]} rotation={[Math.PI, 0, Math.PI]} scale={0.001} />
        <mesh name="Frame" geometry={nodes.Frame.geometry} material={materials['Material.010']} />
        <mesh name="Sky" geometry={nodes.Sky.geometry} material={materials['Material.011']} />
        <mesh name="Art001" geometry={nodes.Art001.geometry} material={materials['Material.009']} position={[4.782, 1.754, 0.002]} />
        <mesh name="Art002" geometry={nodes.Art002.geometry} material={materials['Material.009']} position={[4.782, 1.754, -5.166]} />
        <mesh name="Art003" geometry={nodes.Art003.geometry} material={materials['Material.009']} position={[4.782, 1.754, 5.17]} />
        <mesh name="Art004" geometry={nodes.Art004.geometry} material={materials['Material.009']} position={[-4.782, 1.754, 5.17]} />
        <mesh name="Art005" geometry={nodes.Art005.geometry} material={materials['Material.009']} position={[-4.782, 1.754, 0.002]} />
        <mesh name="Art006" geometry={nodes.Art006.geometry} material={materials['Material.009']} position={[-4.782, 1.754, -5.166]} />
        <mesh name="Water001" geometry={nodes.Water001.geometry} material={materials['Material.001']} morphTargetDictionary={nodes.Water001.morphTargetDictionary} morphTargetInfluences={nodes.Water001.morphTargetInfluences} />
      </group>
    </group>
  )
}

useGLTF.preload('./assets/artgallery.gltf')
